name: Krinry Flutter Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'apk'
        type: string
      mode:
        description: 'Build mode'
        required: true
        default: 'release'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Build APK Release
        run: flutter build apk --release
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: fox-vodafone-release
          path: build/app/outputs/flutter-apk/*.apk
